[Bug] #127 : Fix bugs that do not apply changes when clicking a button
DeveloperAcademy-POSTECH/MC3-Team15-DaeguGoodPriceShop pull request #134
Opened 2022-07-17 02:54 UTC by imparang

# Issue Number
🔒 Close #127 

## New features

- 즐겨찾기 버튼 클릭시 tint color 변경 적용
- 카테고리 버튼 클릭시 tint color 변경 적용
- 카테고리 버튼 클릭시 모달이 올라갔다 내려갔다 적용

## Questions

- 이름이 비슷한 메서드들이 많아서 나중에 리팩토링한다면 네이밍을 다시해야할 것 같아요.

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

2022-07-17 10:04 UTC, sustainable-git requested changes
128번 issue에 대한 commit이 포함되어 있습니다.

2022-07-17 10:07 UTC, sustainable-git commented on DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
> +            categoryModalVC.changeModalHeight(.zero)
filtering도 함께 풀리나요?

2022-07-18 00:15 UTC, imparang commented on DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
> +            categoryModalVC.changeModalHeight(.zero)
옙

2022-07-18 00:15 UTC, imparang commented
> 128번 issue에 대한 commit이 포함되어 있습니다.

머지할 때 처리하겠슴다

2022-07-18 00:59 UTC, merged