[Bug] #140 : Change Annotation Update Method
DeveloperAcademy-POSTECH/MC3-Team15-DaeguGoodPriceShop pull request #141
Opened 2022-07-17 10:58 UTC by Yeongwoo-Poding

# Issue Number
🔒 Close #140

## New features

- 어노테이션 갱신 방법을 전체 삭제 후 추가하는 방식에서 삭제해야 할 어노테이션만 삭제하고 추가해야 할 어노테이션만 추가하는 방식으로 변경

## Review points

- 정상 동작 여부 확인해 주세요

## Questions

- 성능적으로 손해가 있을지 궁금합니다

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

2022-07-17 11:51 UTC, sustainable-git requested changes
이거 제가 한건데요...

2022-07-17 12:05 UTC, sustainable-git reviewed
poding이 작성한 code가 더 범용성이 높을 것 같습니다.

2022-07-17 12:05 UTC, sustainable-git commented on DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
> +            }
해당 logic은 꼭 필요한 부분이었네요

2022-07-18 00:15 UTC, Yeongwoo-Poding commented on DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
> +            }
> 이거 제가 한건데요... [Pull request](https://github.com/DeveloperAcademy-POSTECH/MC3-Team15-DaeguGoodPriceShop/pull/130)

즐겨찾기와 카테고리가 나눠져있는줄 몰랐네요...ㅠ

2022-07-18 00:16 UTC, Yeongwoo-Poding commented
카테고리랑 즐겨찾기가 나누어져 있는지 몰랐네요..ㅠㅠ

2022-07-18 01:58 UTC, merged