[Feature] User Location, Annotation
DeveloperAcademy-POSTECH/MC3-Team15-DaeguGoodPriceShop pull request #26
Opened 2022-07-05 03:06 UTC by Yeongwoo-Poding

# Issue Number
🔒 Close #22 
🔒 Close #25 

## New features

- 유저의 현재 위치를 받아온다
- 지도에 착한 가게 업소 위치에 annotation을 보여준다

## References

- [SampleMapApp](https://github.com/sustainable-git/SampleMapApp)
- [CustomAnnotation](https://kokojong.tistory.com/m/7)

## Checklist

- [x] Is the branch you are merging on correct?
- [x] Do you comply with coding conventions?
- [x] Are there any changes not related to PR?
- [x] Has my code been self-reviewed?

2022-07-05 03:31 UTC, imparang commented on DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
> +    func isShopIncludedCategory(subCategory: String) -> Bool {
얘기해보면 좋을거 같은 부분인데 
Entity에서 computed property와 method는 extension으로 따로 빼서 관리하는 건 어떨지 궁금쓰 하네요.

2022-07-05 03:31 UTC, imparang commented on DaeguGoodPriceShop/DaeguGoodPriceShop/Manager/LocationManager.swift
> +    var initialLocationEvent: (CLLocation) -> Void = { _ in }
@sustainable-git  이거는 스마일한테 물어봐야되는 부분이긴한데 클로저로 따로 놔둔 이유가 궁금합니다.

2022-07-05 03:31 UTC, imparang commented on DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
> +    }
`getDistanceFromUser`, `getDistanceString` 메서드를 사용할거라면 뷰에서 어떤식으로 그려질지 고민하고 해당 값을 어떻게 뷰에 전달해서 사용할 것인지가 중요하겠네요.

2022-07-05 08:24 UTC, Yeongwoo-Poding commented on DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
> +    func isShopIncludedCategory(subCategory: String) -> Bool {
좋은 방법인거 같아요! 바꿔서 다시 커밋 하겠습니다.

2022-07-05 08:24 UTC, Yeongwoo-Poding commented on DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
> +    }
만들면서 생각했던 사용법으로는

1. 가게를 보여줄 때 가까운 순서대로 정렬하기
2. 일정 거리 내의 가게만 보여주기

정도 생각했습니다. 나중에 모달 뷰 작성할때 추가하면 될 것 같아요!

2022-07-05 10:58 UTC, sustainable-git requested changes
수고하셨습니다. 👍

제가 작성한 코드와 포딩이 작성한 코드에서 explicit self 사용에 차이가 있습니다. 논의가 필요할 것 같습니다.
Request를 드리는건 Bug fix commit이 Feature commit과 함께 pull request가 되어서 입니다.
Close의 갯수가 2개인데, #이 붙은 commit은 4개입니다. 혹시 누락인가 하여 말씀드립니다.

2022-07-05 10:58 UTC, sustainable-git commented on DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift
> +        setupUI()
self. 가 빠졌네요 :)

2022-07-05 10:58 UTC, sustainable-git commented on DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
> +    let model = MapModel()
model도 private!

2022-07-05 10:58 UTC, sustainable-git commented on DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
> +        let annotationImage: UIImage!
여기 아랫부분의 code는 AnnotationView에서 그리는게 더 깔끔해요

2022-07-05 10:58 UTC, sustainable-git commented on DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
> +        var annotationView = self.mapView.dequeueReusableAnnotationView(withIdentifier: ShopAnnotationView.identifier)
여기서는 `self.mapView`를 사용하는 것이 좋지 않습니다. 매개변수로 받는 mapView를 사용해주세요.

2022-07-05 11:01 UTC, sustainable-git commented on DaeguGoodPriceShop/DaeguGoodPriceShop/Manager/LocationManager.swift
> +    var initialLocationEvent: (CLLocation) -> Void = { _ in }
@imparang Closure를 이용해서 Binding한 것입니다. Combine을 사용하지 않고 Binding하는 방법입니다. 이렇게 한 이유는 View와 ViewModel을 Combine으로 Binding하고, ViewModel과 Model은 Closure로 Binding하는 단순한 제 습관입니다. 하나로 통일해도 되고, 학습을 위해 둘 다 써봐도 좋을 것 같습니다.

2022-07-05 11:13 UTC, Yeongwoo-Poding commented on DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
> +    let model = MapModel()
viewcontroller에서 modal의 shops 배열에 접근하는 경우가 생겨서 private 선언을 하지 않았는데 private을 하고 getter를 따로 만드는 방법이 좋을까요?

2022-07-05 11:17 UTC, Yeongwoo-Poding commented
> 수고하셨습니다. 👍
> 
> 제가 작성한 코드와 포딩이 작성한 코드에서 explicit self 사용에 차이가 있습니다. 논의가 필요할 것 같습니다. Request를 드리는건 Bug fix commit이 Feature commit과 함께 pull request가 되어서 입니다. Close의 갯수가 2개인데, #이 붙은 commit은 4개입니다. 혹시 누락인가 하여 말씀드립니다.

리뷰 감사합니다! self 사용에 대한 것은 함께 논의해보면 좋을 것 같아요.
Commit은 내일 다시 정리해서 pr 하겠습니다.

2022-07-05 23:11 UTC, sustainable-git commented on DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
> +    let model = MapModel()
MVVM이라는 Architecture는 Data가 Binding되는 방식입니다. ViewController에서 Model에 접근한다면 MVVM이 아닙니다.

- <img src="https://user-images.githubusercontent.com/81242125/177431685-c0da5985-304e-44f6-b9b5-0dd2ff30d644.jpeg">

2022-07-06 01:15 UTC, pis3120 approved these changes

2022-07-06 01:20 UTC, imparang approved these changes

2022-07-06 01:21 UTC, Kelly-Chui approved these changes

2022-07-06 01:21 UTC, merged